### Algebra: Angular Momentum

Reference: http://qutip.org/docs/latest/index.html

In [29]:
import numpy as np
from qutip import *
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
sns.set()

In [30]:
#!pip install qutip

![img](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTRMh9_FL09_N_ftKHwlFvsrwyJQv_wgu_hVg&usqp=CAU)

#### 1. Angular Momentum

In [32]:
sigmaz(),sigmax(),sigmay()

(Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
 Qobj data =
 [[ 1.  0.]
  [ 0. -1.]],
 Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
 Qobj data =
 [[0. 1.]
  [1. 0.]],
 Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
 Qobj data =
 [[0.+0.j 0.-1.j]
  [0.+1.j 0.+0.j]])

In [34]:
np.dot(sigmax(),sigmax())

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])

In [35]:
jmat(1)

(Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
 Qobj data =
 [[0.         0.70710678 0.        ]
  [0.70710678 0.         0.70710678]
  [0.         0.70710678 0.        ]],
 Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
 Qobj data =
 [[0.+0.j         0.-0.70710678j 0.+0.j        ]
  [0.+0.70710678j 0.+0.j         0.-0.70710678j]
  [0.+0.j         0.+0.70710678j 0.+0.j        ]],
 Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
 Qobj data =
 [[ 1.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0. -1.]])

In [44]:
LX = jmat(1,'x')
LY = jmat(1,'y')
LZ = jmat(1,'z')

In [45]:
np.dot(LX,LY) == np.dot(LY,LX)

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [50]:
L_square = (np.dot(LX,LX) + np.dot(LY,LY) +np.dot(LZ,LZ))
L_square

array([[2.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 2.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 2.+0.j]])

In [51]:
jmat(1,"+")

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = False
Qobj data =
[[0.         1.41421356 0.        ]
 [0.         0.         1.41421356]
 [0.         0.         0.        ]]

In [48]:
jmat(3/2,'x')

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.        0.8660254 0.        0.       ]
 [0.8660254 0.        1.        0.       ]
 [0.        1.        0.        0.8660254]
 [0.        0.        0.8660254 0.       ]]

In [49]:
jmat(3/2,'y')

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.+0.j        0.-0.8660254j 0.+0.j        0.+0.j       ]
 [0.+0.8660254j 0.+0.j        0.-1.j        0.+0.j       ]
 [0.+0.j        0.+1.j        0.+0.j        0.-0.8660254j]
 [0.+0.j        0.+0.j        0.+0.8660254j 0.+0.j       ]]

#### 2. Quantum Harmonic Oscillator

In [8]:
momentum(5)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.+0.j         0.-0.70710678j 0.+0.j         0.+0.j
  0.+0.j        ]
 [0.+0.70710678j 0.+0.j         0.-1.j         0.+0.j
  0.+0.j        ]
 [0.+0.j         0.+1.j         0.+0.j         0.-1.22474487j
  0.+0.j        ]
 [0.+0.j         0.+0.j         0.+1.22474487j 0.+0.j
  0.-1.41421356j]
 [0.+0.j         0.+0.j         0.+0.j         0.+1.41421356j
  0.+0.j        ]]

In [9]:
position(5)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.         0.70710678 0.         0.         0.        ]
 [0.70710678 0.         1.         0.         0.        ]
 [0.         1.         0.         1.22474487 0.        ]
 [0.         0.         1.22474487 0.         1.41421356]
 [0.         0.         0.         1.41421356 0.        ]]

In [10]:
create(4)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         0.        ]
 [1.         0.         0.         0.        ]
 [0.         1.41421356 0.         0.        ]
 [0.         0.         1.73205081 0.        ]]

In [11]:
destroy(5)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.         0.        ]
 [0.         0.         1.41421356 0.         0.        ]
 [0.         0.         0.         1.73205081 0.        ]
 [0.         0.         0.         0.         2.        ]
 [0.         0.         0.         0.         0.        ]]

In [12]:
num(4)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 3.]]