### Algebra: Angular Momentum

Reference: http://qutip.org/docs/latest/index.html

In [36]:
import numpy as np
from qutip import *
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
sns.set()

In [37]:
#!pip install qutip

![img](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTRMh9_FL09_N_ftKHwlFvsrwyJQv_wgu_hVg&usqp=CAU)

#### 1. Angular Momentum

In [38]:
jmat(3/2.0,'+')

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         1.73205081 0.         0.        ]
 [0.         0.         2.         0.        ]
 [0.         0.         0.         1.73205081]
 [0.         0.         0.         0.        ]]

In [49]:
LX = jmat(1)[0]
LY = jmat(1)[1]
LZ = jmat(1)[2]

In [58]:
np.dot(LX,LY) == np.dot(LY,LX)

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [57]:
np.dot(LX,LY) - np.dot(LY,LX) 

array([[0.+1.00000000e+00j, 0.+0.00000000e+00j, 0.+0.00000000e+00j],
       [0.+0.00000000e+00j, 0.-8.53284318e-17j, 0.+0.00000000e+00j],
       [0.+0.00000000e+00j, 0.+0.00000000e+00j, 0.-1.00000000e+00j]])

#### 2. Quantum Harmonic Oscillator

In [40]:
momentum(5)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.+0.j         0.-0.70710678j 0.+0.j         0.+0.j
  0.+0.j        ]
 [0.+0.70710678j 0.+0.j         0.-1.j         0.+0.j
  0.+0.j        ]
 [0.+0.j         0.+1.j         0.+0.j         0.-1.22474487j
  0.+0.j        ]
 [0.+0.j         0.+0.j         0.+1.22474487j 0.+0.j
  0.-1.41421356j]
 [0.+0.j         0.+0.j         0.+0.j         0.+1.41421356j
  0.+0.j        ]]

In [15]:
position(5)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.         0.70710678 0.         0.         0.        ]
 [0.70710678 0.         1.         0.         0.        ]
 [0.         1.         0.         1.22474487 0.        ]
 [0.         0.         1.22474487 0.         1.41421356]
 [0.         0.         0.         1.41421356 0.        ]]

In [42]:
create(4)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         0.        ]
 [1.         0.         0.         0.        ]
 [0.         1.41421356 0.         0.        ]
 [0.         0.         1.73205081 0.        ]]

In [16]:
destroy(5)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.         0.        ]
 [0.         0.         1.41421356 0.         0.        ]
 [0.         0.         0.         1.73205081 0.        ]
 [0.         0.         0.         0.         2.        ]
 [0.         0.         0.         0.         0.        ]]

In [41]:
num(4)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 3.]]