### Algebra: Angular Momentum

Reference: http://qutip.org/docs/latest/index.html

In [29]:
import numpy as np
from qutip import *
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
sns.set()

In [30]:
#!pip install qutip

![img](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTRMh9_FL09_N_ftKHwlFvsrwyJQv_wgu_hVg&usqp=CAU)

#### 1. Angular Momentum

In [32]:
sigmaz(),sigmax(),sigmay()

(Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
 Qobj data =
 [[ 1.  0.]
  [ 0. -1.]],
 Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
 Qobj data =
 [[0. 1.]
  [1. 0.]],
 Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
 Qobj data =
 [[0.+0.j 0.-1.j]
  [0.+1.j 0.+0.j]])

In [34]:
np.dot(sigmax(),sigmax())

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])

In [35]:
jmat(1)

(Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
 Qobj data =
 [[0.         0.70710678 0.        ]
  [0.70710678 0.         0.70710678]
  [0.         0.70710678 0.        ]],
 Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
 Qobj data =
 [[0.+0.j         0.-0.70710678j 0.+0.j        ]
  [0.+0.70710678j 0.+0.j         0.-0.70710678j]
  [0.+0.j         0.+0.70710678j 0.+0.j        ]],
 Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
 Qobj data =
 [[ 1.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0. -1.]])

In [44]:
LX = jmat(1,'x')
LY = jmat(1,'y')
LZ = jmat(1,'z')

In [45]:
np.dot(LX,LY) == np.dot(LY,LX)

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [50]:
L_square = (np.dot(LX,LX) + np.dot(LY,LY) +np.dot(LZ,LZ))
L_square

array([[2.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 2.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 2.+0.j]])

In [51]:
jmat(1,"+")

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = False
Qobj data =
[[0.         1.41421356 0.        ]
 [0.         0.         1.41421356]
 [0.         0.         0.        ]]

In [48]:
jmat(3/2,'x')

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.        0.8660254 0.        0.       ]
 [0.8660254 0.        1.        0.       ]
 [0.        1.        0.        0.8660254]
 [0.        0.        0.8660254 0.       ]]

In [49]:
jmat(3/2,'y')

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.+0.j        0.-0.8660254j 0.+0.j        0.+0.j       ]
 [0.+0.8660254j 0.+0.j        0.-1.j        0.+0.j       ]
 [0.+0.j        0.+1.j        0.+0.j        0.-0.8660254j]
 [0.+0.j        0.+0.j        0.+0.8660254j 0.+0.j       ]]

#### 2. Quantum Harmonic Oscillator

In [8]:
momentum(5)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.+0.j         0.-0.70710678j 0.+0.j         0.+0.j
  0.+0.j        ]
 [0.+0.70710678j 0.+0.j         0.-1.j         0.+0.j
  0.+0.j        ]
 [0.+0.j         0.+1.j         0.+0.j         0.-1.22474487j
  0.+0.j        ]
 [0.+0.j         0.+0.j         0.+1.22474487j 0.+0.j
  0.-1.41421356j]
 [0.+0.j         0.+0.j         0.+0.j         0.+1.41421356j
  0.+0.j        ]]

In [9]:
position(5)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.         0.70710678 0.         0.         0.        ]
 [0.70710678 0.         1.         0.         0.        ]
 [0.         1.         0.         1.22474487 0.        ]
 [0.         0.         1.22474487 0.         1.41421356]
 [0.         0.         0.         1.41421356 0.        ]]

In [10]:
create(4)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         0.        ]
 [1.         0.         0.         0.        ]
 [0.         1.41421356 0.         0.        ]
 [0.         0.         1.73205081 0.        ]]

In [11]:
destroy(5)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.         0.        ]
 [0.         0.         1.41421356 0.         0.        ]
 [0.         0.         0.         1.73205081 0.        ]
 [0.         0.         0.         0.         2.        ]
 [0.         0.         0.         0.         0.        ]]

In [12]:
num(4)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 3.]]

#### Random Matrices

- Random hermitian matrix

In [59]:
rand_herm(4)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[-0.50113582+0.j         -0.17222998+0.14571042j  0.        +0.j
  -0.06039662+0.6965142j ]
 [-0.17222998-0.14571042j  0.1689534 +0.j         -0.30474969+0.58835929j
   0.04412378+0.64077284j]
 [ 0.        +0.j         -0.30474969-0.58835929j  0.        +0.j
  -0.45812567-0.08748371j]
 [-0.06039662-0.6965142j   0.04412378-0.64077284j -0.45812567+0.08748371j
   0.75578241+0.j        ]]

- Random Unitary Matrix

In [56]:
rand_unitary(4)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 3.32426091e-01-0.61008781j -2.48216764e-01+0.00742287j
  -3.32218003e-01-0.26721645j  4.67803649e-01-0.23453233j]
 [-6.18056368e-02-0.08520346j  8.37959790e-01-0.35291461j
  -3.11514724e-01-0.25291069j  3.58896057e-05-0.03449434j]
 [-3.17360027e-02-0.48099205j  1.44640852e-01-0.29316018j
   7.90378747e-01+0.10591817j  2.00616601e-02-0.15638388j]
 [-4.27155409e-01+0.30229774j  6.86551818e-02+0.00553252j
   1.09189564e-01+0.0968594j   8.34155661e-01-0.06550129j]]