### Algebra: Tensor Product


1. https://numpy.org/doc/stable/reference/routines.linalg.html
2. http://qutip.org/docs/latest/guide/dynamics/dynamics-master.html

In [2]:
import numpy as np
from qutip import *
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
sns.set()

#### Introduction

#### Constructing composite Hamiltonians

1. Two coupled qubits

In [3]:
sigmaz()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [4]:
identity(2)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

In [5]:
sigmaz()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [6]:
H2 = tensor(sigmaz(), identity(2)) \
    + tensor(identity(2),sigmaz()) \
    + 0.05 * tensor(sigmax(), sigmax())

In [7]:
H2

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 2.    0.    0.    0.05]
 [ 0.    0.    0.05  0.  ]
 [ 0.    0.05  0.    0.  ]
 [ 0.05  0.    0.   -2.  ]]

2. Three Coupled Qubit

In [11]:
H3 = (tensor(sigmaz(), identity(2), identity(2)) +
     tensor(identity(2), sigmaz(), identity(2)) +
    tensor(identity(2), identity(2), sigmaz()) +
     0.5 * tensor(sigmax(), sigmax(), identity(2)) +
     0.25 * tensor(identity(2), sigmax(), sigmax())) 

In [12]:
H3

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[ 3.    0.    0.    0.25  0.    0.    0.5   0.  ]
 [ 0.    1.    0.25  0.    0.    0.    0.    0.5 ]
 [ 0.    0.25  1.    0.    0.5   0.    0.    0.  ]
 [ 0.25  0.    0.   -1.    0.    0.5   0.    0.  ]
 [ 0.    0.    0.5   0.    1.    0.    0.    0.25]
 [ 0.    0.    0.    0.5   0.   -1.    0.25  0.  ]
 [ 0.5   0.    0.    0.    0.    0.25 -1.    0.  ]
 [ 0.    0.5   0.    0.    0.25  0.    0.   -3.  ]]

#### Time Evolution

In [9]:
psi0 = basis(4, 0)
psi0

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]

In [10]:
times = np.linspace(0.0, 10.0, 20)
result = sesolve(H2, psi0, times, [sigmaz()])

In [11]:
result

Result object with sesolve data.
--------------------------------
expect = True
num_expect = 1, num_collapse = 0

In [12]:
result.expect

[array([1.        , 0.99952844, 0.99953782, 0.99999981, 0.99951924,
        0.99954738, 0.99999925, 0.99951025, 0.99955711, 0.99999832,
        0.99950147, 0.999567  , 0.99999702, 0.99949292, 0.99957703,
        0.99999534, 0.99948459, 0.99958719, 0.9999933 , 0.99947651])]

### Scipy

References: https://docs.scipy.org/doc/scipy/reference/linalg.html#module-scipy.linalg