## Satistics - Introduction

https://numpy.org/doc/stable/reference/routines.statistics.html

In [45]:
import numpy as np
import pandas as pd

### 1. Simple Statistical Exploration

In [2]:
A = np.random.rand(10,10)
A

array([[3.34724415e-01, 2.04777906e-01, 1.99627538e-01, 6.35151993e-01,
        1.64831443e-01, 6.17587238e-01, 2.29965338e-01, 2.20358722e-01,
        5.40026796e-01, 1.67814578e-01],
       [3.27191767e-01, 5.79706127e-01, 8.34950616e-01, 7.46962412e-01,
        9.26865452e-01, 6.94767924e-01, 7.15425861e-01, 7.72412109e-01,
        5.82276218e-01, 3.44061867e-01],
       [3.00373097e-01, 4.48969721e-01, 8.25552544e-01, 6.84135674e-02,
        7.58687727e-01, 7.40892096e-01, 9.79354780e-01, 8.16069097e-01,
        8.06915680e-01, 1.77430444e-01],
       [7.12879332e-01, 9.53500293e-01, 6.07398916e-01, 7.18440752e-01,
        4.43100019e-01, 4.90743958e-01, 1.89683400e-01, 4.63703905e-01,
        2.21953702e-01, 9.77571661e-01],
       [6.96730643e-02, 4.08213767e-01, 2.58634172e-01, 7.71271830e-01,
        7.51190806e-01, 2.20280988e-01, 1.60499953e-01, 3.46582902e-01,
        1.47606290e-01, 9.71959879e-02],
       [9.41150053e-02, 5.38185661e-01, 1.56243566e-01, 9.89682258e-01,
   

In [3]:
A.shape

(10, 10)

In [4]:
A.max()

0.9896822575190206

In [5]:
A.min()

0.0002940164103432119

In [6]:
A.mean()

0.426963550934505

In [7]:
np.median(A)

0.3922902994383965

In [8]:
A.std()

0.302883637514015

In [16]:
np.cov(A)

array([[ 0.03646957, -0.0005233 , -0.01214961, -0.010931  ,  0.00516709,
         0.01639217,  0.00085769, -0.01955129, -0.0075899 , -0.01739393],
       [-0.0005233 ,  0.03875586,  0.0349422 , -0.02551802,  0.0327236 ,
         0.01127342,  0.02439794,  0.02412787,  0.02224562,  0.01181266],
       [-0.01214961,  0.0349422 ,  0.10027264, -0.06815371, -0.01485751,
        -0.03772985,  0.06677551,  0.04233022, -0.01535313,  0.01997402],
       [-0.010931  , -0.02551802, -0.06815371,  0.07287469,  0.00474689,
         0.01262358, -0.04076929, -0.02474238, -0.01410162, -0.00335035],
       [ 0.00516709,  0.0327236 , -0.01485751,  0.00474689,  0.06434864,
         0.04276163, -0.00895519, -0.00288492,  0.04569922, -0.00880882],
       [ 0.01639217,  0.01127342, -0.03772985,  0.01262358,  0.04276163,
         0.09344698, -0.00630505, -0.02286083,  0.02749976, -0.01850532],
       [ 0.00085769,  0.02439794,  0.06677551, -0.04076929, -0.00895519,
        -0.00630505,  0.1587303 , -0.01703202

#### Mean and std of row

In [9]:
np.mean(A,axis =0)

array([0.28758393, 0.36989472, 0.5116089 , 0.53047602, 0.51447713,
       0.41262665, 0.50648084, 0.50243897, 0.32965219, 0.30439616])

In [10]:
np.std(A,axis =0)

array([0.22528104, 0.27651716, 0.32022573, 0.3498811 , 0.28038112,
       0.31119565, 0.27434055, 0.29226951, 0.25370837, 0.28242303])

#### Mean and std of col

In [11]:
np.mean(A,axis =1)

array([0.3314866 , 0.65246204, 0.59226588, 0.57789759, 0.32311498,
       0.31236263, 0.36976235, 0.33805777, 0.5069825 , 0.26524318])

In [12]:
np.std(A,axis = 1)

array([0.18117011, 0.18676262, 0.30040868, 0.25610002, 0.24065281,
       0.29000394, 0.37796464, 0.24946805, 0.30441553, 0.27631696])

### 2. Feature Scaling:

- 1. Mini-max scalar

In [106]:
A = (100*np.random.rand(10,10)).astype(int)
A

array([[84, 97, 73, 47, 74, 54, 91, 44, 85, 88],
       [80, 25, 42, 35, 97, 14, 50, 47, 69, 60],
       [39, 49, 92, 12, 73,  0, 31, 65, 45, 65],
       [95, 15, 14, 70, 31, 28, 96,  9, 29, 30],
       [90, 48, 44,  4, 61, 24, 53, 25, 16, 28],
       [22, 69, 36, 47, 27, 88,  9, 52, 38, 41],
       [90,  3, 71, 39, 63, 72, 56,  8, 30, 76],
       [52, 74, 85, 56, 49, 36, 67, 15, 24,  6],
       [ 4, 41, 51, 71, 87, 68, 38, 75,  9, 18],
       [46, 88, 49, 63, 59, 91, 92, 62, 23, 97]])

In [107]:
A_mm = A - A.min()/A.max()-A.min()

In [108]:
A_mm

array([[84., 97., 73., 47., 74., 54., 91., 44., 85., 88.],
       [80., 25., 42., 35., 97., 14., 50., 47., 69., 60.],
       [39., 49., 92., 12., 73.,  0., 31., 65., 45., 65.],
       [95., 15., 14., 70., 31., 28., 96.,  9., 29., 30.],
       [90., 48., 44.,  4., 61., 24., 53., 25., 16., 28.],
       [22., 69., 36., 47., 27., 88.,  9., 52., 38., 41.],
       [90.,  3., 71., 39., 63., 72., 56.,  8., 30., 76.],
       [52., 74., 85., 56., 49., 36., 67., 15., 24.,  6.],
       [ 4., 41., 51., 71., 87., 68., 38., 75.,  9., 18.],
       [46., 88., 49., 63., 59., 91., 92., 62., 23., 97.]])

In [109]:
from sklearn import preprocessing

A_scaled = preprocessing.MinMaxScaler().fit(A).transform(A)
A_scaled

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.87912088, 1.        , 0.75641026, 0.64179104, 0.67142857,
        0.59340659, 0.94252874, 0.53731343, 1.        , 0.9010989 ],
       [0.83516484, 0.23404255, 0.35897436, 0.46268657, 1.        ,
        0.15384615, 0.47126437, 0.58208955, 0.78947368, 0.59340659],
       [0.38461538, 0.4893617 , 1.        , 0.11940299, 0.65714286,
        0.        , 0.25287356, 0.85074627, 0.47368421, 0.64835165],
       [1.        , 0.12765957, 0.        , 0.98507463, 0.05714286,
        0.30769231, 1.        , 0.01492537, 0.26315789, 0.26373626],
       [0.94505495, 0.4787234 , 0.38461538, 0.        , 0.48571429,
        0.26373626, 0.50574713, 0.25373134, 0.09210526, 0.24175824],
       [0.1978022 , 0.70212766, 0.28205128, 0.64179104, 0.        ,
        0.96703297, 0.        , 0.65671642, 0.38157895, 0.38461538],
       [0.94505495, 0.        , 0.73076923, 0.52238806, 0.51428571,
        0.79120879, 0.54022989, 0.        , 0.27631579, 0.76923077],
       [0.52747253, 0.75531915, 0.9102564

- 2. Standard Scalar

In [110]:
A = (100*np.random.rand(10,10)).astype(int)
A

array([[69, 90, 84, 15,  8, 38, 11, 30, 44, 19],
       [ 5, 40, 84, 92, 77, 36, 40, 51, 80, 33],
       [56, 72,  1, 50, 16, 83, 99, 48, 70, 42],
       [47, 50, 56, 56, 25, 24, 22, 86, 20, 32],
       [94, 93, 72, 21, 98, 78, 95, 10,  6, 86],
       [89, 47, 24, 93, 68, 13, 10, 74, 70, 91],
       [14, 27, 94, 67, 97, 31, 98, 53, 97, 35],
       [19, 56, 78, 75, 82, 53, 67, 34, 25, 29],
       [46, 16,  3, 27, 12, 32,  8, 73, 53, 58],
       [37,  3, 96, 77, 13, 36, 21, 64, 66, 94]])

In [111]:
A_ss = A - A.mean()/A.std()

In [112]:
A_ss

array([[67.286851, 88.286851, 82.286851, 13.286851,  6.286851, 36.286851,
         9.286851, 28.286851, 42.286851, 17.286851],
       [ 3.286851, 38.286851, 82.286851, 90.286851, 75.286851, 34.286851,
        38.286851, 49.286851, 78.286851, 31.286851],
       [54.286851, 70.286851, -0.713149, 48.286851, 14.286851, 81.286851,
        97.286851, 46.286851, 68.286851, 40.286851],
       [45.286851, 48.286851, 54.286851, 54.286851, 23.286851, 22.286851,
        20.286851, 84.286851, 18.286851, 30.286851],
       [92.286851, 91.286851, 70.286851, 19.286851, 96.286851, 76.286851,
        93.286851,  8.286851,  4.286851, 84.286851],
       [87.286851, 45.286851, 22.286851, 91.286851, 66.286851, 11.286851,
         8.286851, 72.286851, 68.286851, 89.286851],
       [12.286851, 25.286851, 92.286851, 65.286851, 95.286851, 29.286851,
        96.286851, 51.286851, 95.286851, 33.286851],
       [17.286851, 54.286851, 76.286851, 73.286851, 80.286851, 51.286851,
        65.286851, 32.286851, 23.2868

In [113]:
from sklearn import preprocessing

A_scaled = preprocessing.StandardScaler().fit(A).transform(A)
A_scaled

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 0.74404296,  1.43827016,  0.71272608, -1.55982401, -1.15616234,
        -0.20581431, -0.98088773, -1.0163594 , -0.33063813, -1.22230532],
       [-1.48113224, -0.33299851,  0.71272608,  1.27957194,  0.76151077,
        -0.29936627, -0.19291698, -0.05924965,  0.97738086, -0.70217539],
       [ 0.29205425,  0.80061344, -1.67260716, -0.26918949, -0.93382343,
         1.89910479,  1.41019593, -0.19597962,  0.61404225, -0.36780616],
       [-0.02086102,  0.02125522, -0.09196466, -0.04793785, -0.68369215,
        -0.86067803, -0.68200227,  1.53593327, -1.20265079, -0.73932753],
       [ 1.61325202,  1.54454628,  0.36785862, -1.33857238,  1.34515042,
         1.66522489,  1.30151031, -1.9278925 , -1.71132484,  1.26688788],
       [ 1.43941021, -0.0850209 , -1.01161121,  1.31644722,  0.5113795 ,
        -1.37521381, -1.00805913,  0.98901341,  0.61404225,  1.45264857],
       [-1.16821698, -0.79352836,  1.00011562,  0.35769014,  1.31735805,
        -0.53324617,  1.38302452,  0.03190366

## Baye's Theorem

<img src = "https://miro.medium.com/max/1994/1*CnoTGGO7XeUpUMeXDrIfvA.png" height=400 width=550> <img>

Important Topics:
1. [Bayesian Classifier](https://scikit-learn.org/stable/modules/naive_bayes.html)
2. [Boltzman Machine](https://en.wikipedia.org/wiki/Restricted_Boltzmann_machine)
4. [Quantum Boltzman Machine](https://arxiv.org/abs/1601.02036)

In [48]:
A = (100*np.random.rand(10,4)).astype(int)
A 

array([[56, 71, 59, 85],
       [61,  9, 64, 66],
       [ 5,  4, 11, 45],
       [13, 21, 21, 36],
       [87,  4, 59, 73],
       [72, 46, 36, 60],
       [98, 94, 85, 21],
       [98, 20, 83,  3],
       [ 6, 52, 10, 54],
       [94, 26, 87, 98]])

In [49]:
df = pd.DataFrame(A, columns= ['bud','green','ripen','rotten'],\
                  index= ['apple','guava','mango','orange','banana','pear','papaya','strwberrey','grape','melon'])

In [50]:
df

bud  green  ripen  rotten
apple        56     71     59      85
guava        61      9     64      66
mango         5      4     11      45
orange       13     21     21      36
banana       87      4     59      73
pear         72     46     36      60
papaya       98     94     85      21
strwberrey   98     20     83       3
grape         6     52     10      54
melon        94     26     87      98

In [64]:
df.sum()

bud       590
green     347
ripen     515
rotten    541
dtype: int64

In [63]:
sum(df.sum())

1993

In [53]:
df.loc['apple','bud']

56

In [54]:
df.loc['apple',:]

bud       56
green     71
ripen     59
rotten    85
Name: apple, dtype: int32

In [55]:
df.loc[:,'ripen']

apple         59
guava         64
mango         11
orange        21
banana        59
pear          36
papaya        85
strwberrey    83
grape         10
melon         87
Name: ripen, dtype: int32

- P(ripen|apple) = ?

In [58]:
df.loc['apple','ripen']/df.loc['apple',:].sum()

0.2177121771217712

- P(apple|ripen) = ?

In [59]:
df.loc['apple','ripen']/df.loc[:,'ripen'].sum()

0.1145631067961165

#### Implementing Baye's theorem

- $P(apple|ripen) = \frac{p(ripen|apple)*p(apple)}{p(ripen)}$

In [66]:
p_apple = df.loc['apple',:].sum()/sum(df.sum())
p_ripen_given_apple = df.loc['apple','ripen']/df.loc['apple',:].sum()
p_ripen = df.loc[:,'ripen'].sum()/sum(df.sum())

p_apple_given_ripen = (p_ripen_given_apple*p_apple)/p_ripen
p_apple_given_ripen

0.1145631067961165

#### Mini Assignment:
1. Generate a randum array of size 10 by 10 and convert it to pandas dataframe with column name and row name of your interest
2. Perform feature scaling (minimax scalar and standard scalar) by direct calculation of minimunm, maximum, mean, standard deviation from dataframe/array
3. Implement Scikit-learn preprocessing pipeline to perform feature scaling